name: "go-chatbot"
mode: "debug"
host: "localhost"
start_time: "2022-03-01"
port: 3250
maching_id: 1
log:
  level: "debug"
  filename: "Logger/app.log"
  max_size: 100
  max_age: 30
  max_backups: 7
mysql:
  host: "127.0.0.1"
  port: 3306
  user: "go-chatbot-sql"
  password: "eAryFmcTYyMRDSXM"
  dbname: "go-chatbot-sql"
  max_open_conns: 2000
  max_idle_conns: 500
redis:
  host: "127.0.0.1"
  password: ""
  port: 6379
  db: 0
  pool_size: 100
chat:
  host: "localhost"
  port: 8087
  rout: "/chat"
  key: "question"
email:
  from: "registe@qkgzs.com"
  password: "7289978VISSdx"
  host: "smtp.qcloudmail.com"
  port: 465