export default{
	friends: function(){
		let friendarr=[
			{
				id:1,
				imgurl: 'addUser.png',
				tip:1222,
				name: '好友申请',
				time: new Date(2022,3,7,19,46,35),
				info: "茫茫人海，相见既是缘分",
			},
			{
				id:2,
				imgurl: '1 (2).jpg',
				tip:12,
				name: '高尔基',
				time: new Date(2022,3,6,19,46,35),
				info: "世界上最快而又最慢，最长而又最短，最平凡而又最珍贵，最易被忽视而又最令人后悔的就是时间",
			},
			{
				id:3,
				imgurl: '1 (3).jpg',
				tip:0,
				name: '弗培根',
				time: new Date(2022,1,6,19,46,35),
				info: "真正的敏捷是一件很有价值的事。因为时间是衡量事业的标准，如金钱是衡量货物的标准。",
			},
			{
				id:4,
				imgurl: '1 (4).jpg',
				tip:3,
				name: '文嘉',
				time: new Date(),
				info: "明日复明日，明日何其多！日日待明日，万事成蹉跎。世人皆被明日累，明日无穷老将至。晨昏滚滚水东流。今古悠悠日西坠。百年明日能几何？请君听我《明日歌》。",
			},
			{
				id:5,
				imgurl: '1 (5).jpg',
				tip:3,
				name: 'duan',
				time: new Date(2020,1,6,19,46,35),
				info: "hello",
			},
			{
				id:1,
				imgurl: '1 (6).jpg',
				tip:12,
				name: '好友申请',
				time: new Date(2022,3,7,19,46,35),
				info: "茫茫人海，相见既是缘分",
			},
			{
				id:2,
				imgurl: '1 (7).jpg',
				tip:12,
				name: '高尔基',
				time: new Date(2022,3,6,19,46,35),
				info: "世界上最快而又最慢，最长而又最短，最平凡而又最珍贵，最易被忽视而又最令人后悔的就是时间",
			},
			{
				id:3,
				imgurl: '1 (8).jpg',
				tip:5,
				name: '弗培根',
				time: new Date(2022,1,6,19,46,35),
				info: "真正的敏捷是一件很有价值的事。因为时间是衡量事业的标准，如金钱是衡量货物的标准。",
			},
			{
				id:4,
				imgurl: '1 (9).jpg',
				tip:3,
				name: '文嘉',
				time: new Date(),
				info: "明日复明日，明日何其多！日日待明日，万事成蹉跎。世人皆被明日累，明日无穷老将至。晨昏滚滚水东流。今古悠悠日西坠。百年明日能几何？请君听我《明日歌》。",
			},
			{
				id:5,
				imgurl: '1 (10).jpg',
				tip:3,
				name: 'duan',
				time: new Date(2020,1,6,19,46,35),
				info: "hello",
			},
			{
				id:1,
				imgurl: '1 (11).jpg',
				tip:12,
				name: '好友申请',
				time: new Date(2022,3,7,19,46,35),
				info: "茫茫人海，相见既是缘分",
			},
			{
				id:2,
				imgurl: '1 (12).jpg',
				tip:12,
				name: '高尔基',
				time: new Date(2022,3,6,19,46,35),
				info: "世界上最快而又最慢，最长而又最短，最平凡而又最珍贵，最易被忽视而又最令人后悔的就是时间",
			},
			{
				id:3,
				imgurl: '1 (13).jpg',
				tip:5,
				name: '弗培根',
				time: new Date(2022,1,6,19,46,35),
				info: "真正的敏捷是一件很有价值的事。因为时间是衡量事业的标准，如金钱是衡量货物的标准。",
			},
			{
				id:4,
				imgurl: '1 (14).jpg',
				tip:3,
				name: '文嘉',
				time: new Date(),
				info: "明日复明日，明日何其多！日日待明日，万事成蹉跎。世人皆被明日累，明日无穷老将至。晨昏滚滚水东流。今古悠悠日西坠。百年明日能几何？请君听我《明日歌》。",
			},
			{
				id:5,
				imgurl: '1 (15).jpg',
				tip:3,
				name: 'duan',
				time: new Date(2020,1,6,19,46,35),
				info: "hello",
			},
		];
		return friendarr;
	},
		message:function(){
			let msgs = [
				{
					id: '1231',
					imgurl: '1 (40).jpg',
					message: 'how about you ?',
					types: 0,
					time: new Date(),
					tip: 0,
				},
				{
					id: '1232',
					imgurl: '1 (81).jpg',
					message: 'hello',
					types: 0,
					time: new Date() - 2000,
					tip: 1,
				},
				{
					id: '1231',
					imgurl: '1 (37).jpg',
					message: '你 好你',
					types: 0,
					time: new Date() - 1000*60*6,
					tip: 2,
				},
				{
					id: '1231',
					imgurl: '1 (22).jpg',
					message: 'hellohel lohelloh ellohellohellohellohe llohellohellohe llohellohellohello',
					types: 0,
					time: new Date() - 1000*60*60,
					tip: 3,
				},
				{
					id: '1232',
					imgurl: '1 (81).jpg',
					message: '你好你好你好你好你 好你好你好你好',
					types: 0,
					time: new Date() - 1000*60*64,
					tip: 4,
				},
				{
					id: '1231',
					imgurl: '1 (45).jpg',
					message: 'hell ohellohell ohelloh ellohell',
					types: 0,
					time: new Date() - 1000*60*240,
					tip: 5,
				},
				{
					id: '1231',
					imgurl: '1 (54).jpg',
					message: 'hello',
					types: 0,
					time: new Date() - 1000*60*244,
					tip: 6,
				},
				{
					id: '1232',
					imgurl: '1 (81).jpg',
					message: '1 (109).jpg',
					types: 1,
					time: new Date() - 1000*60*300,
					tip: 7,
				},
				{
					id: '1231',
					imgurl: '1 (75).jpg',
					message: '你 好你',
					types: 0,
					time: new Date() - 1000*60*500,
					tip: 8,
				},
				{
					id: '1231',
					imgurl: '1 (114).jpg',
					message: '1 (106).jpg',
					types: 1,
					time: new Date() - 1000*60*1000,
					tip: 9,
				},
				{
					id: '1232',
					imgurl: '1 (81).jpg',
					message: '你好你好你好你好你 好你好你好你好',
					types: 0,
					time: new Date() - 1000*60*10030,
					tip: 10,
				},
				{
					id: '1231',
					imgurl: '1 (62).jpg',
					message: 'how about you ?',
					types: 0,
					time: new Date() - 1000*60*20000,
					tip: 11,
				},
			];
			return msgs;
		}
}